//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSSR.BSDataMain {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BSDataMain.BsMainDataSoap")]
    public interface BsMainDataSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UspesnaKonekcija", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool UspesnaKonekcija();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZapisiPriem", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ZapisiPriem(System.Data.DataSet data, string KodNaPC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZapisiNaracki", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ZapisiNaracki(System.Data.DataSet data, string KodNaPC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZapisiFakturi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ZapisiFakturi(System.Data.DataSet data, string KodNaPC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZapisiDokumenti", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ZapisiDokumenti(System.Data.DataSet data, string KodNaPC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZapisiSmetki", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ZapisiSmetki(System.Data.DataSet data, string KodNaPC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetZapisaniPriemi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetZapisaniPriemi(string KodNaPC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DaliImaKnizenoDokument", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool DaliImaKnizenoDokument(int DokumentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DaliImaKnizenoPriem", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool DaliImaKnizenoPriem(int tblPriemID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DaliImaKnizenoFaktura", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool DaliImaKnizenoFaktura(int tblFakturaID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DaliImaKnizenoSmetka", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool DaliImaKnizenoSmetka(int tblSmetkaID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetZapisaniDokumenti", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetZapisaniDokumenti(string KodNaPC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetZapisaniFakturi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetZapisaniFakturi(string KodNaPC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetZapisaniSmetki", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetZapisaniSmetki(string KodNaPC);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BsMainDataSoapChannel : BSSR.BSDataMain.BsMainDataSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BsMainDataSoapClient : System.ServiceModel.ClientBase<BSSR.BSDataMain.BsMainDataSoap>, BSSR.BSDataMain.BsMainDataSoap {
        
        public BsMainDataSoapClient() {
        }
        
        public BsMainDataSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BsMainDataSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BsMainDataSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BsMainDataSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool UspesnaKonekcija() {
            return base.Channel.UspesnaKonekcija();
        }
        
        public bool ZapisiPriem(System.Data.DataSet data, string KodNaPC) {
            return base.Channel.ZapisiPriem(data, KodNaPC);
        }
        
        public bool ZapisiNaracki(System.Data.DataSet data, string KodNaPC) {
            return base.Channel.ZapisiNaracki(data, KodNaPC);
        }
        
        public bool ZapisiFakturi(System.Data.DataSet data, string KodNaPC) {
            return base.Channel.ZapisiFakturi(data, KodNaPC);
        }
        
        public bool ZapisiDokumenti(System.Data.DataSet data, string KodNaPC) {
            return base.Channel.ZapisiDokumenti(data, KodNaPC);
        }
        
        public bool ZapisiSmetki(System.Data.DataSet data, string KodNaPC) {
            return base.Channel.ZapisiSmetki(data, KodNaPC);
        }
        
        public System.Data.DataTable GetZapisaniPriemi(string KodNaPC) {
            return base.Channel.GetZapisaniPriemi(KodNaPC);
        }
        
        public bool DaliImaKnizenoDokument(int DokumentID) {
            return base.Channel.DaliImaKnizenoDokument(DokumentID);
        }
        
        public bool DaliImaKnizenoPriem(int tblPriemID) {
            return base.Channel.DaliImaKnizenoPriem(tblPriemID);
        }
        
        public bool DaliImaKnizenoFaktura(int tblFakturaID) {
            return base.Channel.DaliImaKnizenoFaktura(tblFakturaID);
        }
        
        public bool DaliImaKnizenoSmetka(int tblSmetkaID) {
            return base.Channel.DaliImaKnizenoSmetka(tblSmetkaID);
        }
        
        public System.Data.DataTable GetZapisaniDokumenti(string KodNaPC) {
            return base.Channel.GetZapisaniDokumenti(KodNaPC);
        }
        
        public System.Data.DataTable GetZapisaniFakturi(string KodNaPC) {
            return base.Channel.GetZapisaniFakturi(KodNaPC);
        }
        
        public System.Data.DataTable GetZapisaniSmetki(string KodNaPC) {
            return base.Channel.GetZapisaniSmetki(KodNaPC);
        }
    }
}
