CREATE TABLE [dbo].[DW_Knizenja] (
    [ID]                         INT             NULL,
    [DatumNaKnizenje]            DATETIME        NULL,
    [DatumNaPocetok]             DATETIME        NULL,
    [DatumNaKraj]                DATETIME        NULL,
    [Sifra]                      NVARCHAR (20)   NULL,
    [Naziv]                      NVARCHAR (150)  NULL,
    [tipNaArtikal]               INT             NULL,
    [ProdaznaCena]               DECIMAL (18, 2) NULL,
    [Kolicina]                   DECIMAL (12, 4) NULL,
    [Kratenka]                   NVARCHAR (3)    NULL,
    [Procent]                    DECIMAL (4, 2)  NULL,
    [tipNaKnizenje]              INT             NULL,
    [NabavnaCena]                DECIMAL (18, 2) NULL,
    [EdinecnaCena]               DECIMAL (18, 2) NULL,
    [IznosBezDDV]                DECIMAL (18, 2) NULL,
    [IznosDDV]                   DECIMAL (18, 2) NULL,
    [IznosSoDDV]                 DECIMAL (18, 2) NULL,
    [OtpecatenaFiskalna]         INT             NULL,
    [PriemBroj]                  INT             NULL,
    [tblPriemID]                 INT             NULL,
    [SmetkaBroj]                 INT             NULL,
    [fakturaBroj]                INT             NULL,
    [tblArtikalID]               INT             NULL,
    [tblNormativID]              INT             NULL,
    [VrabotenKojJaIzdalSmetkata] NVARCHAR (50)   NULL,
    [KodNaDokument]              NVARCHAR (70)   NULL,
    [Rabat]                      DECIMAL (18, 2) NULL,
    [IznosNaRabat]               DECIMAL (18, 2) NULL,
    [ProdaznaCenaSoRabat]        DECIMAL (18, 2) NULL,
    [tblDokumentID]              INT             NULL,
    [tblObjektiIDOD]             INT             NULL,
    [tblObjektiIDDO]             INT             NULL,
    [DokumentBroj]               INT             NULL,
    [tblSmetkaID]                INT             NULL,
    [tblDDVID]                   INT             NULL,
    [odObjekt]                   NVARCHAR (50)   NULL,
    [doObjekt]                   NVARCHAR (50)   NULL,
    [tblPartnerID]               INT             NULL,
    [AltSifraArtikal]            NVARCHAR (50)   NULL
);

