CREATE TYPE [dbo].[tblArtikal_BulkType] AS TABLE (
    [ID]                         INT             NOT NULL,
    [Sifra]                      NVARCHAR (5)    NULL,
    [Naziv]                      NVARCHAR (150)  NULL,
    [tblDDVStavkaID]             INT             NULL,
    [PodgrupaID]                 INT             NULL,
    [tblEdinecniMerkiID]         INT             NULL,
    [AltNaziv]                   NVARCHAR (150)  NULL,
    [AltSifra]                   NVARCHAR (50)   NULL,
    [KlucniZborovi]              NVARCHAR (300)  NULL,
    [NabavnaCena]                DECIMAL (18, 2) NULL,
    [ProdaznaCena]               DECIMAL (18, 2) NULL,
    [FirmaID]                    INT             NULL,
    [Status]                     INT             NULL,
    [EDMIzlez]                   INT             NULL,
    [KolicinaT]                  DECIMAL (12, 4) NULL,
    [MinimalnaKolicinaNaZaliha]  DECIMAL (9, 2)  NULL,
    [RedenBroj]                  INT             NULL,
    [Barkod1]                    NVARCHAR (50)   NULL,
    [Barkod2]                    NVARCHAR (50)   NULL,
    [AltNaziv2]                  NVARCHAR (150)  NULL,
    [Image]                      NVARCHAR (250)  NULL,
    [SePecatiVoKujna]            BIT             NULL,
    [SePacatiNaSank]             BIT             NULL,
    [DenoviZaGarancija]          INT             NULL,
    [sync_update_peer_timestamp] BIGINT          NULL,
    [sync_update_peer_key]       INT             NULL,
    [sync_create_peer_timestamp] BIGINT          NULL,
    [sync_create_peer_key]       INT             NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC));

