name: Mirror to Azure DevOps Server

on:
  push:
    branches:
      - main  # Change to your default branch if different

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Push to Azure DevOps Server
        env:
          AZDO_PAT: ${{ secrets.AZDO_PAT }}
        run: |
          git config --global user.name "spirodt"
          git config --global user.email "bspirovski@epodrum.mk"  # Change if needed

          # Add remote with PAT authentication (use Basic Auth format)
          git remote add azdo "https://bspirovski:${AZDO_PAT}@devops.epodrum.mk/BSS/BSSR6/_git/BSS7"

          # Push to Azure DevOps
          git push azdo --mirror
